import 'dart:convert';
import 'dart:io';

import 'package:s52_dart/s52_dart.dart';

/// Helpers for loading the real-tile fixtures + the production
/// `s57_lookups.json` asset into Dart test memory.
///
/// The fixtures in `packages/s52_dart/test/fixtures/*.json` are
/// generated by `devtools/charts/extract_s57_fixtures.py` from a
/// representative tile of the SignalK chart provider's `01CGD_ENCs`
/// dataset. They contain real attribute payloads stripped of S-57
/// housekeeping so the style engine sees exactly what it needs to
/// react to.
///
/// The lookup table itself is the same file shipped by the Flutter
/// app at `assets/charts/s57_lookups.json`. Tests load it directly
/// from disk — no Flutter binding required.
class FixtureLoader {
  FixtureLoader._();

  /// Walk upwards from the current working directory until a file
  /// named `assets/charts/s57_lookups.json` is found. That anchors us
  /// to the ZedDisplay repository root regardless of which directory
  /// `dart test` was invoked from.
  static Directory _repoRoot() {
    var dir = Directory.current;
    for (var i = 0; i < 10; i++) {
      final candidate = File('${dir.path}/assets/charts/s57_lookups.json');
      if (candidate.existsSync()) return dir;
      final parent = dir.parent;
      if (parent.path == dir.path) break;
      dir = parent;
    }
    throw StateError(
      'Unable to locate repository root containing '
      'assets/charts/s57_lookups.json (started from '
      '${Directory.current.path})',
    );
  }

  static LookupTable? _cachedLookups;

  /// Load (and cache) the production `s57_lookups.json`.
  static LookupTable loadLookups() {
    final cached = _cachedLookups;
    if (cached != null) return cached;
    final file =
        File('${_repoRoot().path}/assets/charts/s57_lookups.json');
    final raw = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    return _cachedLookups = LookupTable.fromJson(raw);
  }

  /// Enumerate every fixture `S52Feature` across all layer JSON files
  /// under `packages/s52_dart/test/fixtures/`.
  static List<S52Feature> loadAllFixtureFeatures() {
    final dir = Directory(
      '${_repoRoot().path}/packages/s52_dart/test/fixtures',
    );
    if (!dir.existsSync()) {
      throw StateError('Fixture directory does not exist: ${dir.path}');
    }
    final out = <S52Feature>[];
    for (final entry in dir.listSync().whereType<File>()) {
      if (!entry.path.endsWith('.json')) continue;
      final raw = jsonDecode(entry.readAsStringSync()) as List<dynamic>;
      for (final item in raw) {
        out.add(_featureFromJson(item as Map<String, dynamic>));
      }
    }
    return out;
  }

  /// Load fixture features for a single layer name (e.g. `'DEPARE'`).
  static List<S52Feature> loadLayer(String objectClass) {
    final dir = Directory(
      '${_repoRoot().path}/packages/s52_dart/test/fixtures',
    );
    final file = File('${dir.path}/$objectClass.json');
    if (!file.existsSync()) return const [];
    final raw = jsonDecode(file.readAsStringSync()) as List<dynamic>;
    return raw
        .map((e) => _featureFromJson(e as Map<String, dynamic>))
        .toList(growable: false);
  }

  static S52Feature _featureFromJson(Map<String, dynamic> json) {
    final geomName = json['geometryType'] as String;
    final geom = switch (geomName) {
      'point' => S52GeometryType.point,
      'line' => S52GeometryType.line,
      'area' => S52GeometryType.area,
      _ => throw FormatException('Unknown geometryType "$geomName"'),
    };
    return S52Feature(
      objectClass: json['objectClass'] as String,
      geometryType: geom,
      attributes: Map<String, Object?>.from(
        json['attributes'] as Map<String, dynamic>,
      ),
    );
  }
}
